"""empty message

Revision ID: 63015c698a61
Revises: 9724aa2c91dd
Create Date: 2024-02-08 03:00:58.629765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63015c698a61'
down_revision: Union[str, None] = '9724aa2c91dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_1C',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_1c', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('discount_card_number', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.String(length=255), nullable=True))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'chat_id')
    op.drop_table('users_1C')
    # ### end Alembic commands ###
